"""
LLM integration helper for explaining predictions, answering questions, and generating reports.
Uses Ollama API (or similar) for LLM functionality.

This module provides placeholder functions that will be connected to the Ollama API
when the API endpoint is provided by the user.
"""
from typing import Dict, List, Optional, Any
import json
from pathlib import Path
import sys

try:
    import pandas as pd
except ImportError:
    pd = None

# Import config
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    import config as cfg
    OLLAMA_API_URL = getattr(cfg, 'OLLAMA_API_URL', 'http://localhost:11434/api/generate')
    OLLAMA_MODEL = getattr(cfg, 'OLLAMA_MODEL', 'llama3.1:8b')
    OLLAMA_TIMEOUT = getattr(cfg, 'OLLAMA_TIMEOUT', 180)
except ImportError:
    OLLAMA_API_URL = 'http://localhost:11434/api/generate'
    OLLAMA_MODEL = 'llama3.1:8b'
    OLLAMA_TIMEOUT = 180

# Try to import requests for API calls
try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


def _call_ollama_api(prompt: str, context: Optional[str] = None) -> str:
    """
    Call Ollama API with a prompt.
    
    Args:
        prompt: The main prompt/question
        context: Optional context to include
        
    Returns:
        Generated response text
    """
    if not HAS_REQUESTS:
        return "Error: requests library not installed. Install with: pip install requests"
    
    # Combine context and prompt
    full_prompt = f"{context}\n\n{prompt}" if context else prompt
    
    try:
        # Make POST request to Ollama API (long timeout: 8B models can take 1–3 min, especially first run)
        response = requests.post(
            OLLAMA_API_URL,
            json={
                "model": OLLAMA_MODEL,
                "prompt": full_prompt,
                "stream": False
            },
            timeout=OLLAMA_TIMEOUT
        )
        response.raise_for_status()  # Raise exception for bad status codes
        
        result = response.json()
        return result.get("response", "No response generated")
        
    except requests.exceptions.ConnectionError:
        return f"Error: Could not connect to Ollama API at {OLLAMA_API_URL}. Make sure Ollama is running."
    except requests.exceptions.Timeout:
        return (
            "Error: Request to Ollama API timed out. The model may be taking too long to respond.\n\n"
            "Try: (1) Run the request again — the first run is often slow. "
            "(2) In config.py set OLLAMA_TIMEOUT to a higher value (e.g. 300). "
            "(3) Use a smaller model (e.g. llama3.1:3b) if you have limited RAM or CPU."
        )
    except requests.exceptions.RequestException as e:
        return f"Error calling Ollama API: {str(e)}"
    except (KeyError, TypeError) as e:
        return f"Invalid response from Ollama API: {e}"
    except Exception as e:
        return f"Unexpected error: {str(e)}"


def explain_prediction(
    predictions_df: "pd.DataFrame",
    model_info: Dict[str, Any],
    task: str = "breath_hold"
) -> str:
    """
    Generate an explanation of prediction results using LLM.

    Args:
        predictions_df: DataFrame with predictions, confidence, features
        model_info: Dictionary with model name, task, etc.
        task: Task name ("breath_hold" or "gating_ok")

    Returns:
        Explanation text generated by LLM
    """
    if pd is None:
        return "Error: pandas not available"
    if predictions_df is None or len(predictions_df) == 0:
        return "Error: No prediction data to explain."
    if "prediction" not in predictions_df.columns:
        return "Error: Prediction dataframe missing 'prediction' column."

    total_windows = len(predictions_df)
    breath_hold_count = (predictions_df["prediction"] == 1).sum()
    free_breathing_count = total_windows - breath_hold_count
    avg_confidence = predictions_df["confidence"].mean() if "confidence" in predictions_df.columns else 0.0
    
    # Get feature statistics
    feature_stats = {}
    feature_cols = ["vol_mean", "vol_std", "vol_min", "vol_max", "frac_balloon_inflated"]
    for col in feature_cols:
        if col in predictions_df.columns:
            feature_stats[col] = {
                "mean": float(predictions_df[col].mean()),
                "std": float(predictions_df[col].std())
            }
    
    # Build context
    context = f"""
    Prediction Analysis Context:
    - Task: {task}
    - Model: {model_info.get('model_name', 'Unknown')}
    - Total Windows: {total_windows}
    - Breath-hold Windows: {breath_hold_count} ({breath_hold_count/total_windows*100:.1f}%)
    - Free-breathing Windows: {free_breathing_count} ({free_breathing_count/total_windows*100:.1f}%)
    - Average Confidence: {avg_confidence:.3f}
    - Feature Statistics: {json.dumps(feature_stats, indent=2)}
    """
    
    prompt = f"""
    Explain the breathing pattern predictions for this radiation therapy gating data.
    
    The model classified {breath_hold_count} windows as breath-hold and {free_breathing_count} windows as free-breathing.
    The average confidence is {avg_confidence:.3f}.
    
    Provide:
    1. A summary of the breathing patterns observed
    2. Interpretation of the confidence scores
    3. Clinical significance of the findings
    4. Any notable patterns or anomalies
    """
    
    return _call_ollama_api(prompt, context)


def answer_question(
    question: str,
    context: Optional[Dict[str, Any]] = None
) -> str:
    """
    Answer a question about the dataset, models, or predictions using LLM.
    
    Args:
        question: User's question
        context: Optional context dictionary with:
            - dataset_info: Dataset statistics
            - model_info: Model information
            - prediction_info: Recent prediction results
            
    Returns:
        Answer text generated by LLM
    """
    # Build context string
    context_str = ""
    if context:
        if "dataset_info" in context:
            context_str += f"\nDataset Info: {json.dumps(context['dataset_info'], indent=2)}\n"
        if "model_info" in context:
            context_str += f"\nModel Info: {json.dumps(context['model_info'], indent=2)}\n"
        if "prediction_info" in context:
            context_str += f"\nPrediction Info: {json.dumps(context['prediction_info'], indent=2)}\n"
    
    prompt = f"""
    Answer this question about the breathing patterns ML system:
    
    Question: {question}
    
    Provide a clear, helpful answer. If the question is about:
    - Dataset: Use the dataset information provided
    - Models: Use the model information provided
    - Predictions: Use the prediction information provided
    - General usage: Provide instructions based on the system capabilities
    """
    
    return _call_ollama_api(prompt, context_str if context_str else None)


def generate_report(
    analysis_data: Dict[str, Any],
    report_type: str = "patient_summary"
) -> str:
    """
    Generate an analysis report using LLM.
    
    Args:
        analysis_data: Dictionary with analysis data:
            - patient_id: Patient identifier
            - files: List of files analyzed
            - predictions: Prediction results
            - statistics: Statistical summaries
        report_type: Type of report ("patient_summary", "prediction_analysis", "dataset_overview")
        
    Returns:
        Generated report text
    """
    # Prepare report context
    context = f"""
    Report Type: {report_type}
    Analysis Data: {json.dumps(analysis_data, indent=2, default=str)}
    """
    
    if report_type == "patient_summary":
        prompt = """
        Generate a comprehensive patient summary report for radiation therapy gating analysis.
        Include:
        1. Patient overview
        2. Breathing pattern analysis
        3. Prediction summary
        4. Key findings
        5. Recommendations (if applicable)
        """
    elif report_type == "prediction_analysis":
        prompt = """
        Generate a detailed prediction analysis report.
        Include:
        1. Prediction overview
        2. Pattern identification
        3. Confidence analysis
        4. Clinical interpretation
        5. Notable observations
        """
    elif report_type == "dataset_overview":
        prompt = """
        Generate a dataset overview report.
        Include:
        1. Dataset statistics
        2. Data quality assessment
        3. Patient distribution
        4. File format breakdown
        5. Overall summary
        """
    else:
        prompt = f"Generate a {report_type} report based on the provided analysis data."
    
    return _call_ollama_api(prompt, context)


def is_llm_available() -> bool:
    """
    Check if LLM API is available and configured.
    
    Returns:
        True if LLM is configured and available, False otherwise
    """
    if not HAS_REQUESTS:
        return False
    
    try:
        # Check if Ollama is running by trying to list models
        tags_url = OLLAMA_API_URL.replace('/api/generate', '/api/tags')
        response = requests.get(tags_url, timeout=2)
        if response.status_code == 200:
            # Check if the configured model is available
            models_data = response.json()
            available_models = [model.get('name', '') for model in models_data.get('models', [])]
            # Check if our model (or a variant) is available
            model_base = OLLAMA_MODEL.split(':')[0]  # e.g., "llama3.1" from "llama3.1:8b"
            return any(model_base in model for model in available_models)
        return False
    except Exception:
        return False


def get_llm_status() -> Dict[str, Any]:
    """
    Get LLM integration status and configuration.

    Returns:
        Dictionary with status information
    """
    try:
        available = is_llm_available()
        return {
            "available": available,
            "api_url": OLLAMA_API_URL,
            "model": OLLAMA_MODEL,
            "configured": True,
            "requests_installed": HAS_REQUESTS,
            "note": "Ollama API configured. Make sure Ollama is running and the model is available." if available else "Ollama may not be running or model not available. Start Ollama and ensure the model is installed."
        }
    except Exception as e:
        return {
            "available": False,
            "api_url": OLLAMA_API_URL,
            "model": OLLAMA_MODEL,
            "configured": True,
            "requests_installed": HAS_REQUESTS,
            "note": f"Error checking status: {e}"
        }
